[build]
builder = "DOCKERFILE"

[deploy]
preDeployCommand = ["sh -c 'alembic upgrade head && python -m private_client_graph.persistence.seeds.evergreen'"]
healthcheckPath = "/health"
healthcheckTimeout = 60
